fix: Fix workflow python version v3

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -4,7 +4,7 @@ on: [push, pull_request]
 
 jobs:
   test:
-    runs-on: windows-latest
+    runs-on: macos-latest
 
     steps:
       - name: Checkout code
@@ -13,39 +13,39 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
-          python-version: '3.11'
+          python-version: '3.10.20'
 
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-          if ($LASTEXITCODE -eq 0) {
-              Write-Host "Dependencies installed successfully!"
-          } else {
-              Write-Host "Failed to install dependencies!"
-              exit $LASTEXITCODE
-          }
-        shell: pwsh
+          if [ $? -eq 0 ]; then
+              echo "Dependencies installed successfully!"
+          else
+              echo "Failed to install dependencies!"
+              exit 1
+          fi
+        shell: bash
 
       - name: Code Quality Test
         run: |
           flake8 .
-          if ($LASTEXITCODE -eq 0) {
-              Write-Host "Code quality check passed!"
-          } else {
-              Write-Host "Code quality issues detected!"
-              exit $LASTEXITCODE
-          }
-        shell: pwsh
+          if [ $? -eq 0 ]; then
+              echo "Code quality check passed!"
+          else
+              echo "Code quality issues detected!"
+              exit 1
+          fi
+        shell: bash
 
       - name: Code Tests
         run: |
-          $env:PYTHONPATH = "src"
+          export PYTHONPATH=src
           python -m unittest discover -s tests -p '*test.py'
-          if ($LASTEXITCODE -eq 0) {
-              Write-Host "All tests passed!"
-          } else {
-              Write-Host "Some tests failed!"
-              exit $LASTEXITCODE
-          }
-        shell: pwsh
+          if [ $? -eq 0 ]; then
+              echo "All tests passed!"
+          else
+              echo "Some tests failed!"
+              exit 1
+          fi
+        shell: bash
